# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

jobs:
  style-check:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: style-check
          command: |
            pip install --user -U flake8
            python -m flake8 --show-source flow/


  test-3.7: &test-template
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            pip install -U virtualenv --user
            mkdir -p ./venv
            python -m virtualenv ./venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install -U coverage mock

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            coverage run --source=flow/ -m unittest discover tests/
            coverage report -i --include="flow*"

      - store_artifacts:
          path: test-reports
          destination: test-reports

  test-3.6:
    <<: *test-template
    docker:
      - image: circleci/python:3.6
  test-3.5:
    <<: *test-template
    docker:
      - image: circleci/python:3.5
  test-3.4:
    <<: *test-template
    docker:
      - image: circleci/python:3.4
  test-2.7:
    <<: *test-template
    docker:
      - image: circleci/python:2.7

workflows:
  version: 2
  style-check-and-tests:
    jobs:
      - style-check
      - test-2.7:
          requires:
            - style-check
      - test-3.4:
          requires:
            - style-check
      - test-3.5:
          requires:
            - style-check
      - test-3.6:
          requires:
            - style-check
      - test-3.7:
          requires:
            - style-check
